# Server settings
host: '127.0.0.1'
sass:
  sass_dir: _scss
  style: compressed
gems: [jekyll-paginate]

# Global site settings
name: John Doe
description: "I <b>take pride</b> in what I do"
long_description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Ut voluptas pariatur, tenetur placeat exercitationem, dolorum culpa
                  eius tempora odio impedit iusto ab, quae sequi! Accusamus aspernatur
                  exercitationem sunt ex doloremque."
meta_description: "Yucca theme showcase"

settings:
  reveal_animations: true
  typing_animations:
    enable: true
    strings:
      - 'I am a <b>web developer</b>'
      - 'I am a <b>UI designer</b>'
      - 'I am a <b>UX designer</b>'
      - 'I <b>take pride</b> in what I do'

# Plugin settings
markdown: redcarpet
highlighter: rouge

# Blog settings
paginate: 20
baseurl: /
external_blog: true
blog_url: '/blog'

# Site settings
domain_name: 'http://example.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'disqus_shortname'
contact: false
typeform_url: 'https://example.typeform.com/to/xxxxxx'
greeting: true

# Details for the RSS feed generator
url:            'http://example.com/blog'
author:         'John Doe'
authorTwitter:  'JohnDoe'

permalink:       /:year/:title/

# Public profiles
profiles:
  - site: linkedIn
    url: 'https://www.linkedin.com/in/xxxxxxxxxxxxx'
    icon: linkedin
  - site: github
    url: 'https://github.com/xxxxxxxx'
    icon: github
  - site: twitter
    url: 'https://twitter.com/xxxxxxxx'
    icon: twitter
  - site: blog
    url: 'http://example.com/blog'
    icon: edit

experience:
  - date: 12/02/2013
    title: Test
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum praesentium officia,
                  fugit recusandae ipsa, quia velit nulla adipisci?'
  - date: 22/02/2014
    title: Test 2
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum praesentium officia,
                  fugit recusandae ipsa, quia velit nulla adipisci?'
  - date: 05/08/2014
    title: Test 3
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum praesentium officia,
                  fugit recusandae ipsa, quia velit nulla adipisci?'
  - date: 22/01/2015
    title: Test 4
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum praesentium officia,
                  fugit recusandae ipsa, quia velit nulla adipisci?'
  - date: 25/03/2016
    title: Test 4
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum praesentium officia,
                  fugit recusandae ipsa, quia velit nulla adipisci?'

# Skills
skills:
  - name: 'Web Development'
    weight: 50
    color: '#ECE4B7'
    breakdown:
      - name: 'Ruby on Rails'
        weight: 50
        color: '#ab234c'
      - name: 'Typescript'
        weight: 30
        color: '#025D8C'
      - name: 'Angular.js'
        weight: 20
        color: '#ECE4B7'
  - name: 'Mongo DB'
    weight: 20
    color: '#025D8C'
  - name: 'Java'
    weight: 20
    color: '#A9C947'
  - name: 'Node.js'
    weight: 10
    color: '#C9E69A'
    breakdown:
      - name: 'Express.js'
        weight: 40
        color: '#ab234c'
      - name: 'Electron'
        weight: 60
        color: '#025D8C'

languages:
  - name: 'Ruby'
    icon: 'langs/ruby.png'
  - name: 'Javascript'
    icon: 'langs/js.png'
  - name: 'HTML5'
    icon: 'langs/html5.png'
  - name: 'CSS3'
    icon: 'langs/css3.png'
  - name: 'Sass'
    icon: 'langs/sass.png'
  - name: 'Java'
    icon: 'langs/java.png'
  - name: 'PHP'
    icon: 'langs/php.png'
  - name: 'Python'
    icon: 'langs/python.png'
  - name: 'Bash'
    icon: 'langs/bash.png'
  - name: 'C'
    icon: 'langs/c.png'
  - name: 'C++'
    icon: 'langs/c++.png'
  - name: 'Swift'
    icon: 'langs/swift.png'

technologies:
  - name: 'Ruby on Rails'
    icon: 'techs/ror.png'
  - name: 'Node.js'
    icon: 'techs/nodejs.png'
  - name: 'D3.js'
    icon: 'techs/d3.png'
  - name: 'Angular.js'
    icon: 'techs/angular.png'
  - name: 'Bootstrap'
    icon: 'techs/bootstrap.png'
  - name: 'jQuery'
    icon: 'techs/jquery.png'
  - name: 'Android'
    icon: 'techs/android.png'
  - name: 'Git'
    icon: 'techs/git.png'
  - name: 'Jekyll.rb'
    icon: 'techs/jekyll.png'
  - name: 'Unicorn'
    icon: 'techs/unicorn.png'
  - name: 'Nginx'
    icon: 'techs/nginx.png'
  - name: 'PostgreSQL'
    icon: 'techs/postgres.png'
  - name: 'IDA disasm'
    icon: 'techs/ida.png'
  - name: 'OllyDbg'
    icon: 'techs/ollydbg.png'
  - name: 'Radare2'
    icon: 'techs/r2.png'

gallery:
  - category: 'Projects'
    images:
      - name: 'Yucca'
        src: 'https://images.unsplash.com/photo-1476365518243-f738bf58443d?dpr=2&auto=format&fit=crop&w=500&h=800&q=80&cs=tinysrgb&crop='
        description: 'Yucca is an awesome open-source jekyll theme.'
        link: 'https://github.com/FernandoDoming/yucca'
  - category: 'Photography'
    images:
      - name: Lorem ipsum
        thumb:  https://images.unsplash.com/photo-1471070855862-324d571a1857?dpr=1&auto=format&fit=crop&w=800&h=600&q=80&cs=tinysrgb&crop=
        src:  https://images.unsplash.com/photo-1471070855862-324d571a1857?dpr=1&auto=format&fit=crop&w=1600&h=1200&q=80&cs=tinysrgb&crop=
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste amet eum eligendi
                      ut officiis totam rem cum ducimus quam quisquam ipsum adipisci quaerat fugiat odio,
                      doloremque tempora, reprehenderit accusantium quas."
      - name: Lorem ipsum
        thumb:  https://images.unsplash.com/photo-1452127308952-47a699216fc5?dpr=1&auto=format&fit=crop&w=400&h=400&q=80&cs=tinysrgb&crop=
        src:  https://images.unsplash.com/photo-1452127308952-47a699216fc5?dpr=1&auto=format&fit=crop&w=1200&h=1200&q=80&cs=tinysrgb&crop=
      - name: Lorem ipsum
        thumb:  https://images.unsplash.com/photo-1467642511314-5699547ddf30?dpr=1&auto=format&fit=crop&w=400&h=600&q=80&cs=tinysrgb&crop=
        src:  https://images.unsplash.com/photo-1467642511314-5699547ddf30?dpr=1&auto=format&fit=crop&w=800&h=1200&q=80&cs=tinysrgb&crop=
      - name: Lorem ipsum
        thumb:  https://images.unsplash.com/photo-1414433473172-dc6afb63e4ba?dpr=1&auto=format&fit=crop&w=300&h=200&q=80&cs=tinysrgb&crop=
        src:  https://images.unsplash.com/photo-1414433473172-dc6afb63e4ba?dpr=1&auto=format&fit=crop&w=1200&h=800&q=80&cs=tinysrgb&crop=
      - name: Lorem ipsum
        thumb:  https://images.unsplash.com/photo-1476231682828-37e571bc172f?dpr=1&auto=format&fit=crop&w=450&h=620&q=80&cs=tinysrgb&crop=
        src:  https://images.unsplash.com/photo-1476231682828-37e571bc172f?dpr=1&auto=format&fit=crop&w=900&h=1240&q=80&cs=tinysrgb&crop=
      - name: Lorem ipsum
        thumb:  https://images.unsplash.com/photo-1468224970805-92d72c619545?dpr=1&auto=format&fit=crop&w=580&h=400&q=80&cs=tinysrgb&crop=
        src:  https://images.unsplash.com/photo-1468224970805-92d72c619545?dpr=1&auto=format&fit=crop&w=1160&h=800&q=80&cs=tinysrgb&crop=

certifications:
  - name: 'My certification 1'
    link: '#certifications'
    issuer: 'Org 1'
  - name: 'My certification 2'
    img:  'https://www.cybrary.it/wp-content/uploads/2016/06/NewCertificate-1024x697.png'
    link: '#certifications'
    issuer: 'Org 1'
  - name: 'My certification 3'
    img: 'https://www.cybrary.it/wp-content/uploads/2016/06/NewCertificate-1024x697.png'
    link: '#certifications'
    issuer: 'Org 1'
  - name: 'My certification 4'
    link: '#certifications'
    issuer: 'Org 1'

books:
  - name: 'Practical malware analysis'
    cover: 'https://www.nostarch.com/sites/default/files/imagecache/product_full/practical_malware_analysis.png'
    progress: 70%
    link: '#books'
  - name: "The antivirus hacker's handbook"
    cover: 'http://media.wiley.com/product_data/coverImage300/52/11190287/1119028752.jpg'
    progress: 100%
    link: '#books'
  - name: 'The ruby programming language'
    cover: 'https://images-na.ssl-images-amazon.com/images/I/51i0hr6kccL._SX258_BO1,204,203,200_.jpg'
    progress: 50%
    link: '#books'
  - name: 'Javascript: The good parts'
    cover: 'http://akamaicovers.oreilly.com/images/9780596517748/cat.gif'
    progress: 20%
    link: '#books'

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
